# Generated by Django 5.2.6 on 2025-09-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('date',)},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='date',
        ),
    ]
